// Generated by service/scripts/analyze-challenge.ts; bound to source hash, seat and key.
export const challengeAnalysis = {
  "version": 1,
  "sourceHash": "ee510033b7639a8fbb9680effcc6362c4e378d1552742807caa0fda97e04dd38",
  "sourceVersion": 6,
  "keySeq": 75,
  "seat": 2,
  "samples": 96,
  "referenceTile": "6m",
  "method": "paired-hidden-state-v1",
  "policy": "minimum-shanten-visible-outs-v1",
  "rows": [
    {
      "tile": "1m",
      "meanNet": -0.4791666666666667,
      "difference": -0.8125,
      "interval95": [
        -1.4720230367204108,
        -0.1529769632795892
      ],
      "positiveRate": 0.5
    },
    {
      "tile": "2m",
      "meanNet": -1.09375,
      "difference": -1.4270833333333333,
      "interval95": [
        -2.0322720801100282,
        -0.8218945865566384
      ],
      "positiveRate": 0.3541666666666667
    },
    {
      "tile": "3m",
      "meanNet": -1.0416666666666667,
      "difference": -1.375,
      "interval95": [
        -1.9867688618676804,
        -0.7632311381323195
      ],
      "positiveRate": 0.3958333333333333
    },
    {
      "tile": "4m",
      "meanNet": -0.6875,
      "difference": -1.0208333333333333,
      "interval95": [
        -1.6261851895979698,
        -0.41548147706869676
      ],
      "positiveRate": 0.4479166666666667
    },
    {
      "tile": "6m",
      "meanNet": 0.3333333333333333,
      "difference": 0,
      "interval95": [
        0,
        0
      ],
      "positiveRate": 0.59375
    },
    {
      "tile": "7m",
      "meanNet": -1.0416666666666667,
      "difference": -1.375,
      "interval95": [
        -1.9491175532173535,
        -0.8008824467826465
      ],
      "positiveRate": 0.3541666666666667
    },
    {
      "tile": "8m",
      "meanNet": -1.3645833333333333,
      "difference": -1.6979166666666667,
      "interval95": [
        -2.268995860422608,
        -1.1268374729107256
      ],
      "positiveRate": 0.3125
    },
    {
      "tile": "5p",
      "meanNet": -0.25,
      "difference": -0.5833333333333334,
      "interval95": [
        -1.2385980224975652,
        0.07193135583089849
      ],
      "positiveRate": 0.4895833333333333
    },
    {
      "tile": "3p",
      "meanNet": 0.34375,
      "difference": 0.010416666666666666,
      "interval95": [
        -0.47828766930455846,
        0.49912100263789183
      ],
      "positiveRate": 0.6041666666666666
    }
  ],
  "notice": "96 组相同的可行隐藏手牌与余牌顺序，分别试打各候选牌；不使用录像后续摸牌或动作。其后双方按向听数、可见进张及合法胡牌行动。95% 区间只反映抽样误差，未覆盖对手模型偏差；用于关键步训练对照，不能证明真实比赛最优或水平超过选手。各区间为逐项比较，未作多重比较校正。"
} as const;
