import {readFileSync,writeFileSync} from 'node:fs';
import {createChallengeCheckpoint} from '../src/challenge';
import {TableCore} from '../src/table-core';
import {challengeAction,shuffled} from '../src/challenge-policy';
import {BloodEngine} from '../src/engine/blood-engine';
// Offline paired evaluation. No recorded future draw or action enters a rollout.
const record=JSON.parse(readFileSync(process.argv[2]!,'utf8'));
const now=1800000000000,seat=2,keySeq=75,samples=96;
const saved=createChallengeCheckpoint({record,keySeq,seat,seed:20260910},{v:1,kind:'owner',owner:'analysis',tenant:'analysis',exp:now+1000000},'11111111-1111-4111-8111-111111111111',now);
const original=new TableCore(saved);original.join(seat,now);const candidates=[...new Set<string>(original.catalog(seat).publicActions.filter((a:any)=>a.kind==='discard').map((a:any)=>a.tile))];
const known=new Set(original.game.entries('tileFacePublic').map(([id])=>Number(id)));
const unknown=original.game.entries('things').filter(([id,t])=>!known.has(Number(id))&&!(t.slotName.startsWith('hand.')&&t.slotName.endsWith('@'+seat))).map(([id])=>Number(id));
const pool=unknown.map(id=>(original.engine as BloodEngine).tileKeyForId(id)!);
const constraints=Object.values(original.state.players).filter((p:any)=>p.seat!==seat&&!p.hu).map((p:any)=>{
 const events=record.events.filter((e:any)=>e.seq<=keySeq&&e.seat===p.seat),last=events.at(-1);
 return {seat:p.seat,dingque:p.dingque,cleared:last?.action==='discard'&&last.tile[1]!==p.dingque};
});
const results=new Map(candidates.map(tile=>[tile,[] as number[]]));
for(let sample=0;sample<samples;sample++){
 let keys:number[]=[];
 for(let trial=0;trial<10000;trial++){
  keys=shuffled(pool,0x73d51a+sample*10000+trial);const mapping=new Map(unknown.map((id,i)=>[id,keys[i]!]));
  if(constraints.every((c:any)=>!c.cleared||original.game.entries('things').filter(([,t])=>t.slotName.startsWith('hand.')&&t.slotName.endsWith('@'+c.seat)).every(([id])=>'mps'[Math.floor((mapping.get(Number(id))??(original.engine as BloodEngine).tileKeyForId(Number(id))!)/9)]!==c.dingque)))break;
  if(trial===9999)throw new Error('Could not sample a legal hidden hand');
 }
 for(const first of candidates){
  const snapshot=structuredClone(saved),map=new Map(snapshot.engine.secret.tileKeyById);unknown.forEach((id,i)=>map.set(id,keys[i]!));snapshot.engine.secret.tileKeyById=[...map];
  snapshot.challenge!.events=[];snapshot.challenge!.anchors=[-1,-1,-1,-1];snapshot.challenge!.referenceNet=undefined;
  const core=new TableCore(snapshot);core.join(seat,now);let n=0;
  while(!['settling','done'].includes(core.state.phase)&&n<500){const acting=Number(Object.keys(core.windows)[0]);const action=n===0?core.catalog(acting).publicActions.find((a:any)=>a.tile===first):challengeAction(core,acting).action;if(!action)throw new Error('Missing legal analysis action');
   core.submit(acting,{actionId:'a'+n,action:{kind:'aiDecision',decisionId:core.decision(acting)!.decisionId,legalActionId:action.legalActionId}},now+n++);
  }
  if(n>=500)throw new Error('Analysis did not settle');results.get(first)!.push(core.state.players[seat].beans-saved.challenge!.startScores[seat]!);
 }
 if((sample+1)%16===0)console.log(`模拟 ${sample+1}/${samples} 组完成`);
}
const reference=results.get('6m')!,mean=(xs:number[])=>xs.reduce((a,b)=>a+b,0)/xs.length;
const rows=candidates.map(tile=>{const xs=results.get(tile)!,paired=xs.map((x,i)=>x-reference[i]!),difference=mean(paired),se=Math.sqrt(paired.reduce((n,x)=>n+(x-difference)**2,0)/(samples-1)/samples);return {tile,meanNet:mean(xs),difference,interval95:[difference-1.96*se,difference+1.96*se],positiveRate:xs.filter(x=>x>0).length/samples};});
const result={version:1,sourceHash:saved.challenge!.sourceHash,sourceVersion:saved.challenge!.sourceVersion,keySeq,seat,samples,referenceTile:'6m',method:'paired-hidden-state-v1',policy:'minimum-shanten-visible-outs-v1',rows,
 notice:'96 组相同的可行隐藏手牌与余牌顺序，分别试打各候选牌；不使用录像后续摸牌或动作。其后双方按向听数、可见进张及合法胡牌行动。95% 区间只反映抽样误差，未覆盖对手模型偏差；用于关键步训练对照，不能证明真实比赛最优或水平超过选手。各区间为逐项比较，未作多重比较校正。'};
const json=JSON.stringify(result,null,2);writeFileSync(process.argv[3]!,process.argv[3]!.endsWith('.ts')?'// Generated by service/scripts/analyze-challenge.ts; bound to source hash, seat and key.\nexport const challengeAnalysis = '+json+' as const;\n':json+'\n');console.log('关键步模拟对照已保存');
